### ISSUE TITLE
Please add Wemos D1 Mini Pro

### ISSUE THREAD

**Issue by stefanh12** [MattFryer/Board_Identify#6]
The WeMos D1 Mini Pro is not identified, please add the ARDUINO_ESP8266_WEMOS_D1MINIPRO definition

**Comment by MattFryer** [comment]
I've added to the main branch but not yet pushed a new release. Can you test and let me know if it works ok?

**Comment by stefanh12** [comment]
That was fast :) It does work for me on my D1 mini Pro

**Comment by MattFryer** [comment]
Great! I also added the mini lite whilst I was doing it. I’ll check for other WeMos boards and make a new release. It can take a few hours before it makes it to the arduino IDE though.
